import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MainHeader } from "@/components/Header/MainHeader";
import { MainFooter } from "@/components/Footer/MainFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Church App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className="flex flex-col w-screen max-w-[100vw] overflow-x-hidden">
        <MainHeader />
        {children}
        <MainFooter />
      </body>
    </html>
  );
}
